/**
 * GENERATED by `scripts/hand-ingest.mjs` from `art/hands/print/` — the
 * drawings are the source; edit those and run the ingest (§25).
 *
 * Traced over Andika (Andika-Regular.ufo,
 * OFL-1.1, https://github.com/silnrsi/font-andika), so the shapes are
 * a modified version of that face under its licence.
 *
 * Hand units, y up from the baseline. Each stroke is absolute path data in
 * M, L, C and Q, in the order the pen draws it.
 */
import type { Hand } from "./hand";

export const PRINT: Hand = {
  id: "print",
  name: "School Skills Print",
  units: 1000,
  ascent: 1000,
  xHeight: 500,
  descent: -500,
  space: 320,
  glyphs: {
    a: {
      advance: 614,
      strokes: [
        "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
        "M 527 500 L 527 0",
      ],
      forms: {
        own: "single",
        alternates: {
          double: {
            advance: 520,
            strokes: [
              "M 96 378 C 118 450 191 500 275 500 C 377 500 460 426 460 335 L 460 60 C 460 25 350 0 260 0 C 150 0 60 67 60 150 C 60 233 150 300 260 300 C 371 300 460 233 460 150",
            ],
          },
        },
      },
    },
    e: {
      advance: 577,
      strokes: [
        "M 108 270 L 517 270 C 508 395 421 491 312 500 C 204 508 107 425 83 304 C 60 184 117 62 218 17 C 320 -28 434 18 489 125",
      ],
    },
    g: {
      advance: 614,
      strokes: [
        "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
        "M 527 500 L 527 -250 C 527 -375 456 -481 362 -498 C 267 -514 178 -436 154 -315",
      ],
      forms: {
        own: "single",
        alternates: {
          double: {
            advance: 573,
            strokes: [
              "M 424 439 C 355 511 234 521 152 460 C 70 399 60 290 128 217 C 197 145 318 135 400 196 C 482 257 492 366 424 439",
              "M 443 242 C 498 170 513 -60 513 -225 C 513 -377 415 -500 293 -500 C 172 -500 73 -377 73 -225 C 73 -100 140 8 236 41",
            ],
          },
        },
      },
    },
    l: {
      advance: 120,
      strokes: ["M 60 1000 L 60 0"],
    },
    q: {
      advance: 812,
      strokes: [
        "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
        "M 527 500 L 527 -350 C 527 -404 556 -453 602 -480 C 648 -507 706 -507 752 -480",
      ],
      forms: {
        own: "curved",
        alternates: {
          straight: {
            advance: 614,
            strokes: [
              "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
              "M 527 500 L 527 -500",
            ],
          },
        },
      },
    },
    t: {
      advance: 510,
      strokes: [
        "M 180 750 L 180 150 C 180 96 214 47 270 20 C 326 -7 394 -7 450 20",
        "M 60 500 L 340 500",
      ],
      forms: {
        own: "curved",
        alternates: {
          straight: {
            advance: 400,
            strokes: ["M 180 750 L 180 0", "M 60 500 L 340 500"],
          },
        },
      },
    },
  },
};
