/**
 * GENERATED by `scripts/hand-ingest.mjs` from `art/hands/print/` — the
 * drawings are the source; edit those and run the ingest (§25).
 *
 * Traced over Andika (Andika-Regular.ufo,
 * OFL-1.1, https://github.com/silnrsi/font-andika), so the shapes are
 * a modified version of that face under its licence.
 *
 * Hand units, y up from the baseline. Each stroke is absolute path data in
 * M, L, C and Q, in the order the pen draws it.
 */
import type { Hand } from "./hand";

export const PRINT: Hand = {
  id: "print",
  name: "School Skills Print",
  units: 1000,
  ascent: 1000,
  xHeight: 500,
  descent: -500,
  space: 320,
  glyphs: {
    a: {
      advance: 614,
      strokes: [
        "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
        "M 527 500 L 527 0",
      ],
    },
    e: {
      advance: 577,
      strokes: [
        "M 108 270 L 517 270 C 508 395 421 491 312 500 C 204 508 107 425 83 304 C 60 184 117 62 218 17 C 320 -28 434 18 489 125",
      ],
    },
    g: {
      advance: 614,
      strokes: [
        "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
        "M 527 500 L 527 -250 C 527 -375 456 -481 362 -498 C 267 -514 178 -436 154 -315",
      ],
    },
    l: {
      advance: 120,
      strokes: ["M 60 1000 L 60 0"],
    },
    t: {
      advance: 510,
      strokes: [
        "M 180 750 L 180 150 C 180 96 214 47 270 20 C 326 -7 394 -7 450 20",
        "M 60 500 L 340 500",
      ],
    },
  },
};
