/**
 * GENERATED by `scripts/hand-ingest.mjs` from `art/hands/print/` — the
 * drawings are the source; edit those and run the ingest (§25).
 *
 * Traced over Andika (Andika-Regular.ufo,
 * OFL-1.1, https://github.com/silnrsi/font-andika), so the shapes are
 * a modified version of that face under its licence.
 *
 * Hand units, y up from the baseline. Each stroke is absolute path data in
 * M, L, C and Q, in the order the pen draws it.
 */
import type { Hand } from "./hand";

export const PRINT: Hand = {
  id: "print",
  name: "School Skills Print",
  units: 1000,
  ascent: 1000,
  xHeight: 500,
  descent: -500,
  space: 320,
  glyphs: {
    a: {
      advance: 614,
      strokes: [
        "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
        "M 527 500 L 527 0",
      ],
      forms: {
        own: "single",
        alternates: {
          double: {
            advance: 525,
            strokes: [
              "M 112 405 C 143 463 208 500 280 500 C 382 500 465 426 465 335 L 465 30 C 465 2 340 0 240 0 C 130 0 60 60 60 140 C 60 260 320 315 465 295",
            ],
          },
        },
      },
    },
    e: {
      advance: 577,
      strokes: [
        "M 108 270 L 517 270 C 508 395 421 491 312 500 C 204 508 107 425 83 304 C 60 184 117 62 218 17 C 320 -28 434 18 489 125",
      ],
    },
    g: {
      advance: 614,
      strokes: [
        "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
        "M 527 500 L 527 -250 C 527 -375 456 -481 362 -498 C 267 -514 178 -436 154 -315",
      ],
      forms: {
        own: "single",
        alternates: {
          double: {
            advance: 578,
            strokes: [
              "M 434 439 C 365 511 244 521 162 460 C 80 399 70 290 138 217 C 207 145 328 135 410 196 C 492 257 502 366 434 439",
              "M 479 328 C 496 240 508 120 479 -57 C 518 -149 518 -261 479 -352 C 441 -444 370 -500 293 -500 C 196 -500 111 -410 85 -281 C 60 -152 101 -16 186 51",
            ],
          },
        },
      },
    },
    l: {
      advance: 120,
      strokes: ["M 60 1000 L 60 0"],
    },
    q: {
      advance: 812,
      strokes: [
        "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
        "M 527 500 L 527 -350 C 527 -404 556 -453 602 -480 C 648 -507 706 -507 752 -480",
      ],
      forms: {
        own: "curved",
        alternates: {
          straight: {
            advance: 614,
            strokes: [
              "M 476 411 C 397 517 259 530 166 442 C 73 353 60 195 139 89 C 217 -16 355 -30 448 59 C 542 147 554 305 476 411",
              "M 527 500 L 527 -500",
            ],
          },
        },
      },
    },
    t: {
      advance: 510,
      strokes: [
        "M 180 750 L 180 150 C 180 96 214 47 270 20 C 326 -7 394 -7 450 20",
        "M 60 500 L 340 500",
      ],
      forms: {
        own: "curved",
        alternates: {
          straight: {
            advance: 400,
            strokes: ["M 180 750 L 180 0", "M 60 500 L 340 500"],
          },
        },
      },
    },
  },
};
