/**
 * The Dolch sight words, graded.
 *
 * Edward Dolch's 1936 lists are the standard set of high-frequency words that
 * don't reliably yield to phonics — "said", "because", "one" — which is
 * exactly why they're worth drilling by recall rather than sounding out.
 *
 * Graded by AGE rather than by school year on purpose. Dolch's own grades are
 * American ("pre-primer", "primer", "first grade"), this codebase is written
 * in British English, and the mapping between the two systems is approximate
 * anyway. An age band means the same thing in both, and it's what a parent
 * picking a list for their own child actually reasons about.
 *
 * Fry's first 100 is deliberately NOT here as well: roughly four fifths of it
 * is already in Dolch, so a second near-identical list is choice paralysis
 * rather than choice. Parent-authored lists are the answer for anything these
 * don't cover.
 */

export type WordList = {
  id: string;
  name: string;
  /** Who it's for, in the terms a parent will pick by. */
  group: string;
  blurb: string;
  emoji: string;
  words: string[];
};

export const WORD_LISTS: WordList[] = [
  {
    id: "dolch-1",
    name: "First words",
    group: "Ages 4–5",
    blurb: "The first forty. Mostly two and three letters.",
    emoji: "🌱",
    words: [
      "a",
      "and",
      "away",
      "big",
      "blue",
      "can",
      "come",
      "down",
      "find",
      "for",
      "funny",
      "go",
      "help",
      "here",
      "I",
      "in",
      "is",
      "it",
      "jump",
      "little",
      "look",
      "make",
      "me",
      "my",
      "not",
      "one",
      "play",
      "red",
      "run",
      "said",
      "see",
      "the",
      "three",
      "to",
      "two",
      "up",
      "we",
      "where",
      "yellow",
      "you",
    ],
  },
  {
    id: "dolch-2",
    name: "Next steps",
    group: "Ages 5–6",
    blurb: "Colours, numbers and the words that hold a sentence together.",
    emoji: "🚗",
    words: [
      "all",
      "am",
      "are",
      "at",
      "ate",
      "be",
      "black",
      "brown",
      "but",
      "came",
      "did",
      "do",
      "eat",
      "four",
      "get",
      "good",
      "have",
      "he",
      "into",
      "like",
      "must",
      "new",
      "no",
      "now",
      "on",
      "our",
      "out",
      "please",
      "pretty",
      "ran",
      "ride",
      "saw",
      "say",
      "she",
      "so",
      "soon",
      "that",
      "there",
      "they",
      "this",
      "too",
      "under",
      "want",
      "was",
      "well",
      "went",
      "what",
      "white",
      "who",
      "will",
      "with",
      "yes",
    ],
  },
  {
    id: "dolch-3",
    name: "Building up",
    group: "Ages 6–7",
    blurb: "Where phonics starts letting you down — “could”, “know”, “once”.",
    emoji: "🧱",
    words: [
      "after",
      "again",
      "an",
      "any",
      "as",
      "ask",
      "by",
      "could",
      "every",
      "fly",
      "from",
      "give",
      "going",
      "had",
      "has",
      "her",
      "him",
      "his",
      "how",
      "just",
      "know",
      "let",
      "live",
      "may",
      "of",
      "old",
      "once",
      "open",
      "over",
      "put",
      "round",
      "some",
      "stop",
      "take",
      "thank",
      "them",
      "then",
      "think",
      "walk",
      "were",
      "when",
    ],
  },
  {
    id: "dolch-4",
    name: "Getting fluent",
    group: "Ages 7–8",
    blurb: "Longer words, and the ones everyone spells wrong first.",
    emoji: "🏃",
    words: [
      "always",
      "around",
      "because",
      "been",
      "before",
      "best",
      "both",
      "buy",
      "call",
      "cold",
      "does",
      "don't",
      "fast",
      "first",
      "five",
      "found",
      "gave",
      "goes",
      "green",
      "its",
      "made",
      "many",
      "off",
      "or",
      "pull",
      "read",
      "right",
      "sing",
      "sit",
      "sleep",
      "tell",
      "their",
      "these",
      "those",
      "upon",
      "us",
      "use",
      "very",
      "wash",
      "which",
      "why",
      "wish",
      "work",
      "would",
      "write",
      "your",
    ],
  },
  {
    id: "dolch-5",
    name: "Tricky ones",
    group: "Ages 8–9",
    blurb: "“Laugh”, “together”, “myself”. The last of the sight words.",
    emoji: "🔥",
    words: [
      "about",
      "better",
      "bring",
      "carry",
      "clean",
      "cut",
      "done",
      "draw",
      "drink",
      "eight",
      "fall",
      "far",
      "full",
      "got",
      "grow",
      "hold",
      "hot",
      "hurt",
      "if",
      "keep",
      "kind",
      "laugh",
      "light",
      "long",
      "much",
      "myself",
      "never",
      "only",
      "own",
      "pick",
      "seven",
      "shall",
      "show",
      "six",
      "small",
      "start",
      "ten",
      "today",
      "together",
      "try",
      "warm",
    ],
  },
  {
    id: "dolch-nouns",
    name: "Everyday things",
    group: "Ages 5–7",
    blurb:
      "Things you can point at. Good for a reader who's still building up.",
    emoji: "🧸",
    // Dolch's noun list, less "Christmas" and "Santa Claus": a spelling deck
    // has no way to signal that a capital is required, and one of them isn't
    // a single word.
    words: [
      "apple",
      "baby",
      "back",
      "ball",
      "bear",
      "bed",
      "bell",
      "bird",
      "birthday",
      "boat",
      "box",
      "boy",
      "bread",
      "brother",
      "cake",
      "car",
      "cat",
      "chair",
      "chicken",
      "children",
      "coat",
      "corn",
      "cow",
      "day",
      "dog",
      "doll",
      "door",
      "duck",
      "egg",
      "eye",
      "farm",
      "farmer",
      "father",
      "feet",
      "fire",
      "fish",
      "floor",
      "flower",
      "game",
      "garden",
      "girl",
      "goodbye",
      "grass",
      "ground",
      "hand",
      "head",
      "hill",
      "home",
      "horse",
      "house",
      "kitty",
      "leg",
      "letter",
      "man",
      "men",
      "milk",
      "money",
      "morning",
      "mother",
      "name",
      "nest",
      "night",
      "paper",
      "party",
      "picture",
      "pig",
      "rabbit",
      "rain",
      "ring",
      "robin",
      "school",
      "seed",
      "sheep",
      "shoe",
      "sister",
      "snow",
      "song",
      "squirrel",
      "stick",
      "street",
      "sun",
      "table",
      "thing",
      "time",
      "top",
      "toy",
      "tree",
      "watch",
      "water",
      "way",
      "wind",
      "window",
      "wood",
    ],
  },
];

export const WORD_LISTS_BY_ID = new Map(WORD_LISTS.map((l) => [l.id, l]));

/** The list a child of this age is most likely to be working on. */
export function wordListForAge(age: number): WordList {
  if (age <= 5) return WORD_LISTS[0];
  if (age <= 6) return WORD_LISTS[1];
  if (age <= 7) return WORD_LISTS[2];
  if (age <= 8) return WORD_LISTS[3];
  return WORD_LISTS[4];
}
