import type { APIRoute } from "astro";

import { searchIndex } from "./_search";

/**
 * The search index, as a file on disk.
 *
 * A static endpoint rather than a script that writes into `public/`: the index
 * is a view of the ten catalogs, and those are TypeScript modules compiled into
 * this build. Emitting it from a route means it is regenerated by the same
 * command that rebuilds the pages it describes, from the same imports, and
 * cannot be a stale artefact somebody forgot to run — which is the whole
 * failure this story is guarding against. `astro build` writes it to
 * `dist/printables/search-index.json`; nothing runs at request time, here or
 * anywhere else on this site.
 *
 * It is fetched by the island on the front door the first time a parent
 * actually reaches for the search, so the page itself carries none of these
 * bytes — see `Find.tsx`. `scripts/search-index-guard.mjs` reads the file back
 * off disk after the build and fails it if a single sheet in `dist/` is missing
 * from it.
 *
 * `JSON.stringify` without an indent, deliberately: it lands on a phone, and
 * pretty-printing a hundred and nineteen rows would add a fifth to it for the
 * benefit of nobody. The shape is documented where it is defined, in
 * `@/engine/sheets/search`.
 */
export const GET: APIRoute = () =>
  new Response(JSON.stringify(searchIndex()), {
    headers: { "content-type": "application/json" },
  });
