#!/usr/bin/env node
/**
 * Reads a hand's drawings back into the engine (`docs/printables.md` §25).
 *
 * Every `art/hands/<hand>/*.svg` is a template from `hand-template.mjs` with
 * strokes drawn into its `strokes` layer, and this turns the lot into one
 * generated module, `src/engine/sheets/hands/<hand>.ts`: a glyph per
 * character, a stroke per path, in the order the paths sit in the file —
 * which is the order they were drawn, and the order the pen is meant to
 * make them. What one drawing becomes is `scripts/hand/drawing.mjs`, and
 * how the two drawings of a letter taught two ways fold into one glyph is
 * `scripts/hand/forms.mjs`; this is the walk over the directory and the
 * write.
 *
 * Usage:
 *   node scripts/hand-ingest.mjs --hand print
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import prettier from "prettier";

import { readDrawing } from "./hand/drawing.mjs";
import { assemble } from "./hand/forms.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function moduleSource(hand, glyphs) {
  const name = hand.id.toUpperCase().replace(/-/g, "_");
  const traced = hand.tracedOver
    ? ` * Traced over ${hand.tracedOver.family} (${hand.tracedOver.master},\n * ${hand.tracedOver.licence}, ${hand.tracedOver.source}), so the shapes are\n * a modified version of that face under its licence.\n *\n`
    : "";
  return `/**
 * GENERATED by \`scripts/hand-ingest.mjs\` from \`art/hands/${hand.id}/\` — the
 * drawings are the source; edit those and run the ingest (§25).
 *
${traced} * Hand units, y up from the baseline. Each stroke is absolute path data in
 * M, L, C and Q, in the order the pen draws it.
 */
import type { Hand } from "./hand";

export const ${name}: Hand = ${JSON.stringify(
    {
      id: hand.id,
      name: hand.name,
      units: hand.units,
      ascent: hand.ascent,
      xHeight: hand.xHeight,
      descent: hand.descent,
      space: hand.space,
      glyphs,
    },
    null,
    2,
  )};
`;
}

async function main() {
  const at = process.argv.indexOf("--hand");
  const id = at >= 0 ? process.argv[at + 1] : undefined;
  if (!id) throw new Error("--hand is required");
  const dir = join(ROOT, "art", "hands", id);
  const hand = JSON.parse(readFileSync(join(dir, "hand.json"), "utf8"));

  const warnings = [];
  const files = readdirSync(dir)
    .filter((file) => file.endsWith(".svg"))
    .sort();
  if (files.length === 0) throw new Error(`${dir}: no drawings`);
  const drawings = files.map((file) =>
    readDrawing(hand, readFileSync(join(dir, file), "utf8"), file, warnings),
  );
  const glyphs = assemble(hand, drawings, warnings);

  const target = join(ROOT, "src", "engine", "sheets", "hands", `${id}.ts`);
  const options = (await prettier.resolveConfig(target)) ?? {};
  const source = await prettier.format(moduleSource(hand, glyphs), {
    ...options,
    filepath: target,
  });
  writeFileSync(target, source);

  for (const warning of warnings) console.warn(`warning: ${warning}`);
  const total = Object.keys(glyphs).length;
  const count = `${total} glyph${total === 1 ? "" : "s"} from ${files.length} drawing${files.length === 1 ? "" : "s"}`;
  const noted = warnings.length
    ? ` (${warnings.length} warning${warnings.length === 1 ? "" : "s"})`
    : "";
  console.log(`${id}: ${count} → ${target.replace(`${ROOT}/`, "")}${noted}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
