#!/usr/bin/env bash
# Post-deploy smoke checks against the live origin.
#
# Deliberately narrow: this asks "did a working site actually land at this
# URL", not "does the game work" — the browser suite in CI already covers the
# game against the same build artefact. What can only break HERE is the
# delivery: DNS, the certificate, cache headers, the error document.
#
# Three things this got wrong once, all fixed below. Two of them reported a
# failing deploy that was in fact fine, which is the more expensive kind of
# wrong: a smoke check nobody believes is a smoke check nobody reads.
#
# **It only knew about the pages it was written with.** The release that added
# /typing and /spelling passed this script while both were 404. So the page
# list now comes from the deployed sitemap rather than from a list maintained
# by hand: the sitemap is generated by the build, which makes it that build's
# own statement of what should exist, and the one list that cannot drift. A
# page that silently failed to upload now fails here, including a page nobody
# thought to add to this file.
#
# **It ran inside the invalidation window.** CloudFront keeps serving a cached
# negative answer for a few seconds after an invalidation is issued, so the
# first request for a page added in this very release can 404 while the deploy
# is perfectly healthy. Every check therefore retries, with a doubling gap —
# see the budget note below, which a flat 16 seconds was not enough of.
#
# **It lost a race with itself.** `curl | grep -q` under `pipefail` reports
# failure when grep matches early, because grep's exit closes the pipe and
# curl dies of SIGPIPE. The probes no longer pipe into grep at all; the note
# above them has the measurements.
#
# Usage: bash scripts/post-deploy-smoke.sh <base-url>
set -euo pipefail

BASE="${1:?usage: post-deploy-smoke.sh <base-url>}"

# Retries back off: the gap doubles each time, so the waits are 3, 6, 12, 24
# and 48 seconds — about a minute and a half of patience across six attempts,
# and none of it spent when the site is healthy.
#
# It used to be five flat 4-second gaps, or 16 seconds total. That is inside
# CloudFront's propagation window rather than outside it: the release that
# added /about failed this script on /about 404 and the page was serving
# normally by the time anyone looked. A fixed gap has to choose between being
# quick to report a real outage and being patient with a new page; doubling
# does not, because the early attempts stay cheap.
ATTEMPTS="${SMOKE_ATTEMPTS:-6}"
DELAY="${SMOKE_DELAY:-3}"
fails=0

# --- probes: each echoes one word, so a check is a string comparison ---------
#
# None of these pipe curl into `grep -q`, and that is not a style preference.
# `grep -q` exits the instant it matches, which closes the pipe while curl is
# still writing; curl dies of SIGPIPE and exits 141, `pipefail` promotes that
# to the pipeline's status, and the `if` takes the else branch — reporting "no"
# BECAUSE the string was found early enough. Measured against production: 4
# false negatives in 60 runs with pipefail on, 0 with it off. It filed a
# "Production deploy failed" issue for a deploy that was fine.
#
# So each probe fetches into a variable first and matches against that. No
# pipeline, nothing to receive a SIGPIPE, and the result depends on the
# response rather than on who won a race.

status() { curl -sS -o /dev/null -w "%{http_code}" --max-time 15 "$1"; }

body_contains() {
  local body
  body="$(curl -sS --max-time 15 "$1" || true)"
  if grep -qF -- "$2" <<<"$body"; then echo "yes"; else echo "no"; fi
}

header_matches() {
  local headers line
  headers="$(curl -sSI --max-time 15 "$1" | tr -d '\r' || true)"
  # Two greps, but never piped into each other, for the reason above.
  line="$(grep -i -- "^$2:" <<<"$headers" || true)"
  if grep -qi -- "$3" <<<"$line"; then echo "yes"; else echo "no"; fi
}

# --- the retry harness -------------------------------------------------------

# try <label> <expected> <probe> [args...]
#
# The probe is passed unevaluated so it can be run again. Anything it writes to
# stderr is dropped and a non-zero exit is swallowed — a probe that fails to run
# is simply a probe that did not return what we wanted, and gets another go.
try() {
  local label="$1" expected="$2"
  shift 2
  local actual="" attempt=1 wait="$DELAY"
  while [ "$attempt" -le "$ATTEMPTS" ]; do
    actual="$("$@" 2>/dev/null || true)"
    if [ "$actual" = "$expected" ]; then
      if [ "$attempt" -eq 1 ]; then
        echo "  ✓ ${label}"
      else
        # Worth saying out loud. A check that needs three goes today is a check
        # that needs six after the next thing slows down.
        echo "  ✓ ${label} — after ${attempt} attempts"
      fi
      return 0
    fi
    if [ "$attempt" -lt "$ATTEMPTS" ]; then
      sleep "$wait"
      wait=$((wait * 2))
    fi
    attempt=$((attempt + 1))
  done
  echo "  ✗ ${label} — got '${actual}', want '${expected}'"
  fails=$((fails + 1))
  return 0
}

echo "Smoke-testing ${BASE}"

# --- is anything there at all? -----------------------------------------------

# Before anything else, because every check below retries: against a dead host
# each one would burn its full budget on connection timeouts and the job would
# hit its own timeout long before it finished reporting. One clear failure now
# beats thirty slow ones.
try "landing page serves" "200" status "${BASE}/"
if [ "$fails" -gt 0 ]; then
  echo "✗ the origin is not serving — stopping here rather than timing out"
  exit 1
fi

# --- every page the deployed build claims to have ----------------------------

echo "Pages, from the deployed sitemap:"

# Sitemap entries are absolute and always carry the *canonical* host, because
# that is what a sitemap is for. Only the path is used here, and it is probed
# against the base we were asked to test — otherwise pointing this script at a
# preview origin would quietly check production and pass.
locs() {
  curl -sS --max-time 15 "$1" | grep -o "<loc>[^<]*</loc>" |
    sed -e "s|<[^>]*>||g" -e "s|^https\{0,1\}://[^/]*||"
}

# The `|| true` is load-bearing under `set -e`: `grep -o` exits non-zero when a
# sitemap contains no entries, and an assignment whose command substitution
# fails aborts the script — which is how an empty sitemap made this exit
# silently instead of reporting the empty sitemap. Let it produce nothing and
# let the count guard below say so.
pages=""
for map in $(locs "${BASE}/sitemap-index.xml" || true); do
  pages="${pages}$(locs "${BASE}${map}" || true)
"
done

pagecount=0
while IFS= read -r path; do
  if [ -n "$path" ]; then
    try "${path}" "200" status "${BASE}${path}"
    pagecount=$((pagecount + 1))
  fi
done <<<"$pages"

# An unreadable sitemap would otherwise leave the loop above with nothing to do
# and report a clean run — the precise failure this section exists to catch.
# The site has had more than five pages since its first deploy.
if [ "$pagecount" -lt 5 ]; then
  echo "  ✗ the sitemap yielded only ${pagecount} page(s), so nothing was really checked"
  fails=$((fails + 1))
else
  # Only that the list was worth walking. Whether each page served is the
  # per-page result above, which is where a failure gets reported.
  echo "  ✓ ${pagecount} pages listed in the sitemap"
fi

# --- the game routes ---------------------------------------------------------
#
# Deliberately NOT in the sitemap: each is a `client:only` island whose
# prerendered body is two words, so they carry `noindex` and are filtered out
# in astro.config.mjs. That is correct for search and it silently removed them
# from the loop above, which discovers pages FROM the sitemap — leaving the
# three most important URLs on the site unchecked after a deploy.
#
# So they are named here. A new world means a new line here as well as an entry
# in src/engine/worlds.ts; there is no way to derive one from the other in a
# script that only has an origin to talk to.
echo "Game routes (noindex, so not in the sitemap):"
for path in /flash-cards/ /spelling/play/ /typing/; do
  try "${path}" "200" status "${BASE}${path}"
  # The noindex is the point of excluding them, so it is worth asserting: a
  # game route that lost its robots tag would start competing with the content
  # page written to rank for exactly that query.
  try "${path} is noindex" "yes" \
    body_contains "${BASE}${path}" 'name="robots" content="noindex'
done

# --- everything that isn't a page --------------------------------------------

echo "Delivery:"
try "sitemap serves" "200" status "${BASE}/sitemap-index.xml"
try "robots serves" "200" status "${BASE}/robots.txt"
try "manifest serves" "200" status "${BASE}/manifest.webmanifest"

# These four caught a real outage: a custom `fileOptions` list in sst.config.ts
# replaced SST's default `**` catch-all, so every file not matching a listed
# pattern was never uploaded. Pages all served fine; the PWA, the icons and the
# social card were simply absent. Check one of each shape that isn't a document
# — the sitemap loop above cannot see any of these.
try "service worker serves" "200" status "${BASE}/sw.js"
try "favicon serves" "200" status "${BASE}/favicon.svg"
try "apple touch icon serves" "200" status "${BASE}/apple-touch-icon.png"
try "OG card serves" "200" status "${BASE}/og-default.png"

# A missing error document makes CloudFront answer 502 instead of 404 — which
# is exactly what happened the first time this site was deployed.
try "unknown path 404s (not 502)" "404" status "${BASE}/definitely-not-a-page"

# The title is the cheapest proof we're serving OUR site and not a parked page
# or a stale distribution.
try "landing page contains the site name" "yes" \
  body_contains "${BASE}/" "School Skills"

# HTML must revalidate. If it ever ships immutable, a deploy becomes invisible
# for up to a year and no amount of redeploying fixes it for existing visitors.
try "HTML is revalidated" "yes" \
  header_matches "${BASE}/" "cache-control" "must-revalidate"

if [ "$fails" -gt 0 ]; then
  echo "✗ ${fails} smoke check(s) failed"
  exit 1
fi
echo "✓ all smoke checks passed"
