/**
 * The words Frost Keys builds its lessons out of (docs/typing.md §5.3).
 *
 * Filtering "words a child can type with only `f j d k s l`" needs something
 * to filter. The Dolch lists in `decks/wordlists.ts` are a few hundred words —
 * enough to be a spelling syllabus, nowhere near enough to survive that filter
 * — so this is a few thousand instead, commonest first, so that a lesson
 * asking for "the twenty-five" or "the hundred" (§5.6, lessons 41 and 48) is a
 * `slice` rather than a second list to keep in step with this one.
 *
 * Nothing here decides anything. The generator picks, the ladder filters, and
 * `keys.ts` says what a child has met; this file is the bag they all reach
 * into. That is why it exports data and no functions — a helper here would be
 * a place for the curriculum to leak into the corpus.
 *
 * ── This file must never be reachable from `decks/index.ts` ──────────────────
 * `decks/index.ts` is the front door for every island on the site — flash
 * cards, spelling, the record book, the print shop — and a module in its graph
 * is shipped to all of them, whole. The last time that was got wrong, an import
 * of the passage library from `decks/typing.ts` took the shared chunk from
 * 46 KB to 222 KB, which is why thirty-three verses are written out by hand in
 * that file today. This is the same trap one file over, and it is a bigger one:
 * the corpus is the largest thing in the epic.
 *
 * A comment would not have stopped it the first time, so the ban is a lint
 * rule — `local/no-corpus-in-decks` in `eslint.config.mjs`, over
 * `src/engine/decks/**`, naming this paragraph as its reason.
 *
 * The way past it is already in the type. `TypingConfig.words` carries a run's
 * own text, so the ladder screen — inside the typing island, where the corpus
 * belongs — generates a passage and hands it over in the config, and the deck
 * layer builds cards out of `config.words` exactly as it does for a
 * parent-authored drill. `lessons.ts` stays importable from `decks/` because
 * it holds titles and pass criteria and not one word a child ever types; this
 * file is the half that must stay on the other side of the wall.
 *
 * ── Where the words came from ───────────────────────────────────────────────
 * Written for this repository. No corpus file was copied in, so there is no
 * upstream licence riding on it and nothing to re-check when a dependency
 * changes hands.
 *
 * The first hundred are the common rank order of written English, which is a
 * fact about the language rather than anybody's dataset, and the two hundred
 * after them keep to roughly that order. Past three hundred the words are
 * grouped by sense in bands of decreasing frequency, commoner bands first — an
 * honest description of what the order is worth, and enough for its only two
 * consumers, which take the first twenty-five and the first hundred.
 * Selection leant on the Dolch and Fry sight-word sets already in
 * `decks/wordlists.ts` for the early bands and on what a primary reader
 * actually meets for the rest.
 *
 * The sentences and passages are original prose written for this file. That is
 * deliberate rather than lazy: real prose arrives with curly quotation marks,
 * en dashes and accents, none of which a US ANSI board can produce, and typing
 * marks exactly — a passage carrying one is unpassable rather than hard. The
 * ladder's Scripture is not duplicated here either; `decks/typing.ts` holds
 * thirty-three verses for the free-play levels and the reason it holds them is
 * the paragraph above.
 *
 * ── House rules for adding a word ───────────────────────────────────────────
 *   - **Typeable on the board.** Every character must have a `strokeFor`
 *     (`engine/keyboard.ts`): ASCII letters, and `'` where a contraction needs
 *     one. No curly quotes, no accents, no dashes that are not the hyphen.
 *     `lexicon.test.ts` walks every character of every word for this.
 *   - **Lowercase, and no proper nouns**, except where English will not have
 *     it: `I`, and the days and months. All three are capitalised here for the
 *     same reason they are capitalised on a page, and `unlockedAt` keeps them
 *     out of a child's way until block 4 teaches the shifts. Every other name
 *     lives in the sentence pool, in a sentence, where it reads as a name
 *     rather than as a capitalised noun.
 *   - **British spelling**, as everywhere in this repo. A child copies what is
 *     on screen, so the choice costs nothing and being consistent is worth
 *     something.
 *   - **Something a child can picture**, and nothing that needs a content
 *     warning. This is read alone, at five, with no teacher beside them.
 *   - **No duplicates**, across every band. A word twice is a word twice as
 *     likely to be drawn, which is a frequency claim nobody made.
 */

/**
 * The corpus, commonest first.
 *
 * A single array rather than a band per export, because the order across the
 * bands is the thing being asserted and an array of arrays lets the order
 * inside one band drift out of line with the whole. The bands are comments,
 * which is what they are: an explanation of how it was assembled, and no part
 * of what it means.
 */
export const WORDS: readonly string[] = [
  // ── The first hundred ──────────────────────────────────────────────────────
  // The usual rank order of written English. Lesson 48 is this slice exactly.
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "I",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",

  // ── The second hundred ─────────────────────────────────────────────────────
  "is",
  "was",
  "are",
  "been",
  "has",
  "had",
  "were",
  "said",
  "more",
  "much",
  "many",
  "made",
  "may",
  "part",
  "find",
  "long",
  "down",
  "own",
  "right",
  "old",
  "tell",
  "ask",
  "went",
  "men",
  "read",
  "need",
  "land",
  "home",
  "move",
  "try",
  "kind",
  "hand",
  "picture",
  "again",
  "change",
  "off",
  "play",
  "spell",
  "air",
  "away",
  "animal",
  "house",
  "point",
  "page",
  "letter",
  "mother",
  "answer",
  "found",
  "study",
  "still",
  "learn",
  "should",
  "world",
  "high",
  "every",
  "near",
  "add",
  "food",
  "between",
  "under",
  "never",
  "same",
  "another",
  "sound",
  "great",
  "little",
  "help",
  "put",
  "does",
  "before",
  "must",
  "big",
  "such",
  "why",
  "ago",
  "boy",
  "girl",
  "small",
  "end",
  "let",
  "line",
  "turn",
  "cause",
  "mean",
  "differ",
  "man",
  "here",
  "thing",
  "name",
  "very",
  "through",
  "show",
  "each",
  "set",
  "three",
  "word",

  // ── The third hundred ──────────────────────────────────────────────────────
  "water",
  "call",
  "keep",
  "eye",
  "light",
  "head",
  "left",
  "start",
  "next",
  "hold",
  "run",
  "walk",
  "open",
  "close",
  "carry",
  "stop",
  "began",
  "grow",
  "took",
  "river",
  "four",
  "state",
  "once",
  "book",
  "hear",
  "stand",
  "country",
  "plant",
  "last",
  "school",
  "father",
  "tree",
  "city",
  "earth",
  "eyes",
  "young",
  "talk",
  "soon",
  "list",
  "song",
  "leave",
  "family",
  "body",
  "music",
  "colour",
  "mark",
  "often",
  "until",
  "mile",
  "night",
  "ship",
  "half",
  "second",
  "enough",
  "plain",
  "usual",
  "ready",
  "above",
  "ever",
  "red",
  "though",
  "feel",
  "top",
  "morning",
  "held",
  "white",
  "sea",
  "idea",
  "life",
  "face",
  "watch",
  "far",
  "sun",
  "few",
  "seem",
  "fall",
  "car",
  "care",
  "group",
  "true",
  "friend",
  "money",
  "map",
  "sat",
  "hard",
  "story",
  "green",
  "hour",
  "wall",
  "wait",

  // ── People, and what they are to each other ────────────────────────────────
  "mum",
  "dad",
  "baby",
  "brother",
  "sister",
  "child",
  "children",
  "aunt",
  "uncle",
  "cousin",
  "granny",
  "grandad",
  "parent",
  "neighbour",
  "teacher",
  "class",
  "friends",
  "team",
  "club",
  "doctor",
  "nurse",
  "farmer",
  "baker",
  "driver",
  "pilot",
  "sailor",
  "painter",
  "builder",
  "singer",
  "dancer",
  "player",
  "winner",
  "helper",
  "leader",
  "captain",
  "king",
  "queen",
  "prince",
  "knight",
  "giant",
  "pirate",
  "everyone",
  "someone",
  "nobody",
  "anybody",
  "both",
  "person",

  // ── The body, and how it feels ─────────────────────────────────────────────
  "hair",
  "ear",
  "ears",
  "nose",
  "mouth",
  "tooth",
  "teeth",
  "tongue",
  "chin",
  "cheek",
  "neck",
  "arm",
  "elbow",
  "wrist",
  "finger",
  "thumb",
  "hands",
  "leg",
  "knee",
  "ankle",
  "foot",
  "feet",
  "toe",
  "heart",
  "bone",
  "skin",
  "voice",
  "smile",
  "laugh",
  "tear",
  "sleep",
  "dream",
  "tired",
  "hungry",
  "thirsty",
  "warm",
  "cold",
  "sore",
  "hurt",
  "better",
  "sick",
  "strong",
  "weak",
  "happy",
  "sad",
  "cross",
  "kindly",
  "gentle",
  "brave",
  "afraid",
  "proud",
  "sorry",
  "glad",
  "calm",
  "quiet",
  "loud",

  // ── Home, and the things in it ─────────────────────────────────────────────
  "door",
  "window",
  "floor",
  "roof",
  "stairs",
  "room",
  "kitchen",
  "bathroom",
  "bedroom",
  "garden",
  "gate",
  "fence",
  "path",
  "shed",
  "table",
  "chair",
  "bed",
  "sofa",
  "shelf",
  "cupboard",
  "drawer",
  "lamp",
  "clock",
  "mirror",
  "carpet",
  "curtain",
  "blanket",
  "pillow",
  "towel",
  "soap",
  "brush",
  "comb",
  "cup",
  "mug",
  "plate",
  "bowl",
  "spoon",
  "fork",
  "knife",
  "pan",
  "pot",
  "kettle",
  "jug",
  "bottle",
  "basket",
  "box",
  "bag",
  "key",
  "lock",
  "bell",
  "phone",
  "radio",
  "torch",
  "candle",
  "rug",
  "toy",
  "ball",
  "doll",
  "puzzle",
  "game",
  "kite",
  "drum",
  "whistle",

  // ── School ─────────────────────────────────────────────────────────────────
  "pencil",
  "pen",
  "paper",
  "rubber",
  "ruler",
  "glue",
  "scissors",
  "crayon",
  "chalk",
  "board",
  "desk",
  "lesson",
  "reading",
  "writing",
  "maths",
  "science",
  "history",
  "spelling",
  "number",
  "count",
  "sum",
  "question",
  "test",
  "prize",
  "report",
  "project",
  "library",
  "poem",
  "rhyme",
  "sentence",
  "paragraph",
  "chapter",
  "title",
  "cover",
  "author",
  "note",
  "chart",
  "graph",
  "shape",
  "circle",
  "square",
  "triangle",
  "corner",
  "middle",
  "side",
  "edge",
  "playground",
  "break",
  "dinner",
  "homework",
  "uniform",
  "assembly",
  "trip",

  // ── Animals ────────────────────────────────────────────────────────────────
  "dog",
  "cat",
  "puppy",
  "kitten",
  "bird",
  "fish",
  "frog",
  "duck",
  "hen",
  "chick",
  "cow",
  "pig",
  "sheep",
  "lamb",
  "goat",
  "horse",
  "pony",
  "donkey",
  "rabbit",
  "mouse",
  "rat",
  "fox",
  "wolf",
  "bear",
  "deer",
  "lion",
  "tiger",
  "monkey",
  "elephant",
  "giraffe",
  "zebra",
  "camel",
  "whale",
  "dolphin",
  "shark",
  "seal",
  "crab",
  "snail",
  "worm",
  "bee",
  "wasp",
  "ant",
  "fly",
  "moth",
  "spider",
  "beetle",
  "snake",
  "lizard",
  "turtle",
  "owl",
  "robin",
  "swan",
  "goose",
  "eagle",
  "parrot",
  "penguin",
  "hedgehog",
  "squirrel",
  "badger",
  "otter",
  "nest",
  "wing",
  "feather",
  "tail",
  "paw",
  "fur",
  "shell",
  "egg",
  "burrow",
  "hive",

  // ── Food and drink ─────────────────────────────────────────────────────────
  "bread",
  "butter",
  "cheese",
  "milk",
  "toast",
  "jam",
  "honey",
  "cake",
  "biscuit",
  "bun",
  "pie",
  "pudding",
  "soup",
  "rice",
  "pasta",
  "beans",
  "peas",
  "carrot",
  "potato",
  "tomato",
  "onion",
  "cabbage",
  "lettuce",
  "cucumber",
  "mushroom",
  "apple",
  "pear",
  "plum",
  "peach",
  "banana",
  "orange",
  "lemon",
  "grape",
  "berry",
  "cherry",
  "melon",
  "meat",
  "chicken",
  "sausage",
  "salad",
  "salt",
  "pepper",
  "sugar",
  "flour",
  "sauce",
  "juice",
  "tea",
  "drink",
  "breakfast",
  "lunch",
  "supper",
  "picnic",
  "meal",
  "plateful",
  "taste",
  "sweet",
  "sour",
  "fresh",

  // ── Clothes ────────────────────────────────────────────────────────────────
  "coat",
  "hat",
  "cap",
  "scarf",
  "glove",
  "boot",
  "shoe",
  "sock",
  "shirt",
  "jumper",
  "dress",
  "skirt",
  "trousers",
  "shorts",
  "jacket",
  "belt",
  "button",
  "pocket",
  "zip",
  "lace",
  "hood",
  "sleeve",
  "collar",
  "apron",
  "pyjamas",
  "slipper",
  "ribbon",
  "badge",

  // ── Outside — weather, sky, land, water, growing things ────────────────────
  "sky",
  "cloud",
  "rain",
  "snow",
  "ice",
  "frost",
  "wind",
  "storm",
  "thunder",
  "lightning",
  "sunshine",
  "shadow",
  "rainbow",
  "moon",
  "star",
  "sunset",
  "sunrise",
  "hill",
  "mountain",
  "valley",
  "field",
  "farm",
  "wood",
  "forest",
  "beach",
  "sand",
  "shore",
  "island",
  "lake",
  "pond",
  "stream",
  "waterfall",
  "wave",
  "tide",
  "rock",
  "stone",
  "mud",
  "puddle",
  "grass",
  "leaf",
  "leaves",
  "branch",
  "root",
  "seed",
  "flower",
  "petal",
  "rose",
  "daisy",
  "bush",
  "hedge",
  "weed",
  "acorn",
  "pine",
  "oak",
  "fruit",
  "harvest",
  "spring",
  "summer",
  "autumn",
  "winter",

  // ── Town, travel and machines ──────────────────────────────────────────────
  "town",
  "village",
  "street",
  "road",
  "lane",
  "shop",
  "market",
  "bank",
  "church",
  "castle",
  "museum",
  "park",
  "bridge",
  "tower",
  "station",
  "platform",
  "ticket",
  "train",
  "bus",
  "tram",
  "lorry",
  "van",
  "taxi",
  "bicycle",
  "wheel",
  "engine",
  "motor",
  "boat",
  "sail",
  "anchor",
  "harbour",
  "aeroplane",
  "rocket",
  "space",
  "planet",
  "camera",
  "computer",
  "screen",
  "keyboard",
  "machine",
  "tool",
  "hammer",
  "nail",
  "ladder",
  "rope",
  "wire",
  "battery",
  "switch",
  "handle",
  "wheelbarrow",
  "spade",
  "bucket",
  "hose",
  "tent",
  "torchlight",
  "journey",
  "traffic",

  // ── Time, and counting it ──────────────────────────────────────────────────
  "today",
  "tomorrow",
  "yesterday",
  "week",
  "month",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
  "January",
  "February",
  "March",
  "April",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
  "minute",
  "moment",
  "noon",
  "midnight",
  "afternoon",
  "evening",
  "birthday",
  "holiday",
  "weekend",
  "early",
  "late",
  "always",
  "sometimes",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "twenty",
  "thirty",
  "forty",
  "fifty",
  "hundred",
  "thousand",
  "million",
  "third",
  "fourth",
  "fifth",
  "quarter",
  "double",
  "pair",
  "dozen",

  // ── Doing words ────────────────────────────────────────────────────────────
  // The band the middle of the ladder leans on hardest: a lesson of thirty
  // words that are all nouns reads like a shopping list, and a sentence needs
  // a verb before it needs anything else.
  "jump",
  "hop",
  "skip",
  "climb",
  "crawl",
  "swim",
  "dive",
  "ride",
  "drive",
  "dance",
  "sing",
  "shout",
  "whisper",
  "speak",
  "listen",
  "notice",
  "wonder",
  "guess",
  "remember",
  "forget",
  "believe",
  "decide",
  "choose",
  "wish",
  "hope",
  "worry",
  "laughed",
  "cried",
  "shouted",
  "asked",
  "answered",
  "waited",
  "played",
  "worked",
  "helped",
  "wanted",
  "looked",
  "walked",
  "jumped",
  "opened",
  "closed",
  "pulled",
  "pushed",
  "carried",
  "dropped",
  "picked",
  "packed",
  "filled",
  "emptied",
  "poured",
  "mixed",
  "baked",
  "cooked",
  "washed",
  "cleaned",
  "tidied",
  "swept",
  "painted",
  "drew",
  "wrote",
  "spelt",
  "counted",
  "measured",
  "built",
  "fixed",
  "broke",
  "mended",
  "cut",
  "tore",
  "folded",
  "tied",
  "knotted",
  "sewed",
  "planted",
  "dug",
  "watered",
  "gathered",
  "fed",
  "fetched",
  "chased",
  "caught",
  "threw",
  "kicked",
  "hit",
  "rolled",
  "spun",
  "slid",
  "slipped",
  "fell",
  "stood",
  "lay",
  "knelt",
  "leant",
  "reached",
  "stretched",
  "bent",
  "lifted",
  "hugged",
  "waved",
  "pointed",
  "knocked",
  "rang",
  "sounded",
  "won",
  "lost",
  "scored",
  "raced",
  "ran",
  "hurried",
  "rushed",
  "stopped",
  "started",
  "finished",
  "ended",
  "stayed",
  "arrived",
  "returned",
  "visited",
  "travelled",
  "moved",
  "landed",
  "flew",
  "sank",
  "floated",
  "melted",
  "froze",
  "burnt",
  "shone",
  "glowed",
  "sparkled",
  "grew",
  "changed",
  "learnt",
  "taught",
  "showed",
  "told",
  "searched",
  "hunted",
  "hid",
  "appeared",
  "vanished",
  "followed",
  "led",
  "shared",
  "gave",
  "brought",
  "sent",
  "posted",
  "bought",
  "sold",
  "paid",
  "saved",
  "spent",
  "borrowed",
  "lent",
  "owned",
  "kept",
  "placed",
  "hung",
  "stuck",
  "pressed",
  "squeezed",
  "shook",
  "tapped",
  "rubbed",
  "wiped",
  "dried",
  "soaked",
  "splashed",
  "swung",
  "bounced",
  "crashed",
  "smashed",
  "banged",
  "clapped",
  "cheered",
  "yawned",
  "slept",
  "woke",
  "dressed",
  "brushed",
  "combed",
  "ate",
  "drank",
  "tasted",
  "smelt",
  "touched",
  "felt",
  "heard",
  "saw",
  "knew",
  "thought",
  "understood",
  "explained",
  "described",
  "invited",
  "thanked",
  "promised",
  "agreed",
  "argued",
  "obeyed",
  "allowed",
  "tried",
  "practised",
  "improved",
  "managed",
  "succeeded",
  "failed",
  "repeated",
  "continued",

  // ── Describing words ───────────────────────────────────────────────────────
  "large",
  "huge",
  "tiny",
  "tall",
  "short",
  "wide",
  "narrow",
  "thick",
  "thin",
  "deep",
  "shallow",
  "heavy",
  "empty",
  "full",
  "clean",
  "dirty",
  "dusty",
  "muddy",
  "wet",
  "dry",
  "damp",
  "hot",
  "cool",
  "freezing",
  "boiling",
  "sunny",
  "cloudy",
  "rainy",
  "windy",
  "snowy",
  "stormy",
  "misty",
  "foggy",
  "bright",
  "dark",
  "shiny",
  "dull",
  "clear",
  "cloudier",
  "soft",
  "smooth",
  "rough",
  "sharp",
  "blunt",
  "sticky",
  "slippery",
  "fluffy",
  "furry",
  "prickly",
  "fierce",
  "wild",
  "tame",
  "noisy",
  "silent",
  "busy",
  "lazy",
  "fast",
  "slow",
  "quick",
  "sudden",
  "steady",
  "careful",
  "careless",
  "clever",
  "wise",
  "silly",
  "funny",
  "serious",
  "cheerful",
  "friendly",
  "polite",
  "rude",
  "honest",
  "patient",
  "helpful",
  "useful",
  "useless",
  "lucky",
  "unlucky",
  "special",
  "ordinary",
  "strange",
  "familiar",
  "important",
  "difficult",
  "easy",
  "simple",
  "possible",
  "impossible",
  "certain",
  "unsure",
  "correct",
  "wrong",
  "perfect",
  "beautiful",
  "pretty",
  "handsome",
  "ugly",
  "lovely",
  "horrible",
  "delicious",
  "tasty",
  "sweeter",
  "salty",
  "spicy",
  "hungrier",
  "sleepy",
  "awake",
  "alive",
  "dead",
  "older",
  "modern",
  "ancient",
  "broken",
  "whole",
  "flat",
  "round",
  "curved",
  "straight",
  "crooked",
  "odd",
  "single",
  "blue",
  "yellow",
  "purple",
  "brown",
  "black",
  "grey",
  "golden",
  "silver",
  "pink",

  // ── Joining, pointing and placing ──────────────────────────────────────────
  // The small words a sentence is held together with. They matter to a typing
  // corpus out of proportion to their meaning: they are short, they repeat,
  // and they are what makes generated text read like English rather than like
  // a list of nouns.
  "below",
  "across",
  "along",
  "around",
  "behind",
  "beside",
  "beneath",
  "beyond",
  "inside",
  "outside",
  "towards",
  "against",
  "without",
  "within",
  "during",
  "since",
  "while",
  "unless",
  "although",
  "however",
  "instead",
  "perhaps",
  "maybe",
  "almost",
  "already",
  "afterwards",
  "meanwhile",
  "suddenly",
  "quickly",
  "slowly",
  "quietly",
  "loudly",
  "gently",
  "carefully",
  "happily",
  "sadly",
  "safely",
  "nearly",
  "rather",
  "quite",
  "really",
  "truly",
  "surely",
  "hardly",
  "together",
  "apart",
  "forward",
  "backward",
  "upward",
  "downward",
  "everywhere",
  "somewhere",
  "anywhere",
  "nowhere",
  "everything",
  "something",
  "anything",
  "nothing",
  "whatever",
  "whenever",
  "wherever",
  "whose",
  "whom",
  "yourself",
  "myself",
  "himself",
  "herself",
  "ourselves",
  "themselves",

  // ── Longer words, for the blocks that are about staying at it ──────────────
  // Blocks 8 to 10 ask for sixty, eighty and a hundred and twenty words at a
  // stretch (§5.6), and a passage of nothing but three-letter words is a
  // different exercise from the one those lessons mean.
  "adventure",
  "beginning",
  "butterfly",
  "celebrate",
  "chocolate",
  "classroom",
  "collection",
  "companion",
  "competition",
  "conversation",
  "creature",
  "curious",
  "dangerous",
  "daughter",
  "decision",
  "delighted",
  "different",
  "direction",
  "discover",
  "distance",
  "elephants",
  "equipment",
  "everybody",
  "excellent",
  "excited",
  "exercise",
  "expensive",
  "experiment",
  "explorer",
  "favourite",
  "following",
  "fortunate",
  "frightened",
  "furniture",
  "gathering",
  "generous",
  "grandmother",
  "happiness",
  "increase",
  "information",
  "interesting",
  "invitation",
  "kindness",
  "knowledge",
  "language",
  "listening",
  "machinery",
  "magnificent",
  "measurement",
  "medicine",
  "memories",
  "mysterious",
  "newspaper",
  "notebook",
  "opposite",
  "particular",
  "peaceful",
  "photograph",
  "practice",
  "prepared",
  "probably",
  "restaurant",
  "sandwich",
  "scientist",
  "seaside",
  "several",
  "shoulder",
  "situation",
  "somebody",
  "surprise",
  "telephone",
  "television",
  "temperature",
  "thoughtful",
  "treasure",
  "umbrella",
  "understand",
  "vegetable",
  "wonderful",

  // ── More doing words, in the plain form ────────────────────────────────────
  // The band above is mostly past tense, because that is the tense a story is
  // told in. This one is the form a child meets in an instruction, which is
  // the other half of what they will ever be asked to type.
  "bring",
  "buy",
  "catch",
  "climbing",
  "cook",
  "draw",
  "drop",
  "eat",
  "enter",
  "escape",
  "fill",
  "finish",
  "fold",
  "follow",
  "hang",
  "hide",
  "hunt",
  "join",
  "knock",
  "lead",
  "lift",
  "live",
  "lose",
  "love",
  "march",
  "mend",
  "mind",
  "miss",
  "mix",
  "obey",
  "offer",
  "order",
  "pack",
  "pass",
  "pick",
  "plan",
  "please",
  "pour",
  "pull",
  "push",
  "race",
  "reach",
  "ring",
  "rise",
  "roll",
  "rub",
  "save",
  "search",
  "sell",
  "send",
  "serve",
  "sew",
  "shake",
  "share",
  "shine",
  "shoot",
  "shut",
  "sink",
  "sit",
  "slide",
  "smell",
  "sort",
  "spend",
  "spill",
  "spread",
  "stay",
  "steal",
  "step",
  "stick",
  "stir",
  "strike",
  "sweep",
  "swing",
  "teach",
  "thank",
  "throw",
  "tidy",
  "travel",
  "treat",
  "trust",
  "visit",
  "wake",
  "wander",
  "warn",
  "wash",
  "waste",
  "wear",
  "weigh",
  "win",
  "wipe",
  "wrap",
  "write",
  "yawn",
  "hoping",
  "making",
  "taking",
  "giving",
  "living",
  "coming",
  "going",
  "doing",
  "being",
  "having",
  "getting",
  "running",
  "sitting",
  "putting",
  "cutting",
  "swimming",
  "shopping",
  "stopping",
  "playing",
  "helping",
  "looking",
  "walking",
  "talking",
  "waiting",
  "working",
  "watching",
  "washing",
  "cleaning",
  "cooking",
  "baking",
  "growing",
  "learning",
  "teaching",
  "singing",
  "dancing",
  "drawing",
  "painting",
  "counting",

  // ── Number work ────────────────────────────────────────────────────────────
  // Block 6 is the number row and block 10 mixes digits into prose (§5.6), and
  // the words around a number are as much of that lesson as the digits are.
  "addition",
  "subtract",
  "multiply",
  "divide",
  "equal",
  "total",
  "amount",
  "pattern",
  "size",
  "weight",
  "length",
  "height",
  "width",
  "metre",
  "centimetre",
  "kilogram",
  "gram",
  "litre",
  "degree",
  "angle",
  "cube",
  "cone",
  "oval",
  "diamond",
  "arrow",
  "curve",
  "grid",
  "column",
  "row",
  "tally",
  "average",
  "data",
  "result",
  "method",
  "reason",
  "rule",
  "fact",
  "estimate",
  "sequence",
  "scale",
  "level",
  "record",
  "target",
  "goal",
  "score",
  "price",
  "cost",
  "coin",
  "pound",
  "penny",
  "pence",
  "bill",
  "receipt",
  "measure",
  "compare",

  // ── Materials, and the way the world works ────────────────────────────────
  "metal",
  "plastic",
  "cotton",
  "wool",
  "leather",
  "clay",
  "brick",
  "iron",
  "steel",
  "copper",
  "rust",
  "dust",
  "smoke",
  "flame",
  "fire",
  "coal",
  "oil",
  "fuel",
  "steam",
  "liquid",
  "solid",
  "heat",
  "energy",
  "force",
  "gravity",
  "magnet",
  "motion",
  "balance",
  "weather",
  "climate",
  "season",
  "nature",
  "insect",
  "plants",
  "roots",
  "stem",
  "bark",
  "trunk",
  "soil",
  "compost",
  "seedling",
  "blossom",
  "pollen",
  "nectar",
  "feathers",
  "scales",
  "claws",
  "whiskers",
  "hoof",
  "horn",
  "antler",
  "flock",
  "herd",
  "swarm",
  "shoal",

  // ── Stories, and the things that only happen in them ──────────────────────
  "dragon",
  "fairy",
  "wizard",
  "witch",
  "magic",
  "wand",
  "sword",
  "shield",
  "armour",
  "cave",
  "tunnel",
  "ghost",
  "monster",
  "hero",
  "quest",
  "legend",
  "tale",
  "riddle",
  "mystery",
  "clue",
  "secret",
  "chest",
  "crown",
  "jewel",
  "pearl",
  "throne",
  "palace",
  "cottage",
  "swamp",
  "desert",
  "jungle",
  "ocean",
  "voyage",
  "compass",
  "lantern",
  "scroll",
  "spellbook",
  "potion",
  "curse",
  "wishes",
  "kingdom",
  "villager",
  "stranger",
  "traveller",
  "warrior",
  "guard",
  "servant",
  "merchant",
  "beggar",
  "orphan",
  "twin",
  "rescue",
  "escaped",

  // ── Games, music and making things ────────────────────────────────────────
  "football",
  "cricket",
  "tennis",
  "netball",
  "rugby",
  "cycling",
  "skipping",
  "chess",
  "cards",
  "marbles",
  "match",
  "referee",
  "medal",
  "trophy",
  "coach",
  "training",
  "fitness",
  "piano",
  "guitar",
  "violin",
  "flute",
  "trumpet",
  "tune",
  "band",
  "choir",
  "concert",
  "stage",
  "audience",
  "sketch",
  "model",
  "statue",
  "design",
  "craft",
  "sticker",
  "glitter",
  "beads",
  "thread",
  "needle",
  "scrapbook",
  "album",
  "photo",
  "poster",
  "banner",
  "costume",
  "mask",
  "puppet",
  "theatre",

  // ── Places a child is taken ───────────────────────────────────────────────
  "hospital",
  "office",
  "factory",
  "garage",
  "hotel",
  "cafe",
  "cinema",
  "stadium",
  "airport",
  "lighthouse",
  "windmill",
  "barn",
  "stable",
  "kennel",
  "zoo",
  "farmyard",
  "orchard",
  "meadow",
  "moor",
  "cliff",
  "canal",
  "junction",
  "roundabout",
  "pavement",
  "crossing",
  "postbox",
  "postcard",
  "parcel",
  "envelope",
  "address",
  "stamp",
  "delivery",
  "queue",
  "trolley",
  "counter",
  "checkout",
  "bargain",
  "dentist",
  "ambulance",
  "bandage",
  "plaster",
  "cough",
  "sneeze",
  "illness",
  "healthy",
  "safety",

  // ── Feelings, and the words for thinking about them ───────────────────────
  "anger",
  "joy",
  "fear",
  "pride",
  "courage",
  "comfort",
  "patience",
  "respect",
  "honesty",
  "manners",
  "promise",
  "excitement",
  "sympathy",
  "loneliness",
  "friendship",
  "trouble",
  "argument",
  "apology",
  "forgiveness",
  "praise",
  "blame",
  "reward",
  "punishment",
  "warning",
  "advice",
  "opinion",
  "memory",
  "dreams",
  "curiosity",
  "shock",
  "relief",
  "worried",
  "nervous",
  "confident",
  "jealous",
  "grateful",
  "hopeful",
  "cheerless",
  "content",
  "eager",
  "bored",
  "amused",
  "puzzled",
  "confused",
  "determined",
  "disappointed",

  // ── Everyday extras ───────────────────────────────────────────────────────
  "midday",
  "tonight",
  "someday",
  "moments",
  "minutes",
  "seconds",
  "hours",
  "weeks",
  "months",
  "years",
  "ages",
  "people's",
  "children's",
  "everyone's",
  "brother's",
  "sister's",
  "teacher's",
  "father's",
  "mother's",
  "dog's",
  "cat's",
  "friend's",
  "houses",
  "gardens",
  "streets",
  "shops",
  "schools",
  "books",
  "pages",
  "letters",
  "words",
  "lines",
  "stories",
  "poems",
  "pictures",
  "colours",
  "shapes",
  "numbers",
  "answers",
  "questions",
  "lessons",
  "games",
  "toys",
  "balls",
  "boxes",
  "bags",
  "keys",
  "cups",
  "plates",
  "spoons",
  "forks",
  "knives",
  "chairs",
  "tables",
  "doors",
  "windows",
  "walls",
  "floors",
  "roofs",
  "trees",
  "flowers",
  "birds",
  "dogs",
  "cats",
  "horses",
  "sheepdog",
  "rabbits",
  "mice",
  "insects",
  "clouds",
  "stars",
  "rivers",
  "hills",
  "fields",
  "beaches",
  "mountains",
  "islands",
  "boats",
  "trains",
  "buses",
  "cars",
  "bikes",
  "roads",
  "bridges",
  "towns",
  "cities",
  "villages",
  "countries",
  "families",
  "teachers",
  "doctors",
  "farmers",
  "drivers",
  "players",
  "winners",
  "teams",
  "clubs",
  "parties",
  "presents",
  "candles",
  "balloons",
  "invitations",
  "holidays",
  "weekends",
  "mornings",
  "evenings",
  "nights",
  "seasons",
  "winters",
  "summers",
  "showers",
  "puddles",
  "rainbows",
  "snowman",
  "sledge",
  "skates",
  "gloves",
  "boots",
  "scarves",
  "jumpers",
  "shirts",
  "socks",
  "shoes",
  "pockets",
  "buttons",
  "ribbons",
  "sandwiches",
  "biscuits",
  "cakes",
  "apples",
  "oranges",
  "bananas",
  "carrots",
  "potatoes",
  "tomatoes",
  "sweets",
  "drinks",
  "meals",
  "picnics",
  "kitchens",
  "gardening",
  "tidying",
  "sharing",
  "thinking",
  "wondering",
  "laughing",
  "smiling",
  "crying",
  "shouting",
  "whispering",
  "jumping",
  "hopping",
  "riding",
  "driving",
  "flying",
  "sailing",
  "digging",
  "planting",
  "building",
  "mending",
  "colouring",
  "measuring",
  "weighing",
  "sorting",
  "matching",
  "checking",
  "finishing",
  "starting",
  "trying",
  "practising",
  "improving",
  "remembering",
  "forgetting",
  "understanding",

  // ── Short words, because a small alphabet needs them ──────────────────────
  // The first four blocks unlock a few letters at a time, and a corpus of
  // eight-letter words filtered to nine letters comes back nearly empty. These
  // are the ones that survive.
  "ill",
  "ink",
  "jet",
  "jog",
  "keg",
  "kid",
  "kit",
  "lid",
  "lip",
  "lit",
  "log",
  "lot",
  "mad",
  "mat",
  "met",
  "mob",
  "mop",
  "nap",
  "net",
  "nib",
  "nod",
  "nut",
  "oar",
  "oat",
  "pad",
  "pal",
  "pat",
  "peg",
  "pet",
  "pin",
  "pip",
  "pit",
  "pod",
  "pop",
  "pup",
  "rag",
  "ram",
  "rap",
  "rib",
  "rid",
  "rig",
  "rim",
  "rip",
  "rob",
  "rod",
  "rot",
  "sap",
  "shy",
  "sip",
  "sir",
  "ski",
  "sly",
  "sob",
  "son",
  "sow",
  "spy",
  "tab",
  "tag",
  "tan",
  "tap",
  "tar",
  "tie",
  "tin",
  "tip",
  "ton",
  "tow",
  "tub",
  "tug",
  "vet",
  "vow",
  "wag",
  "war",
  "wax",
  "web",
  "wed",
  "wig",
  "wit",
  "wok",
  "yak",
  "yam",
  "yes",
  "yet",
  "bat",
  "bin",
  "bit",
  "bud",
  "bug",
  "cab",
  "cot",
  "cub",
  "den",
  "dig",
  "dim",
  "dip",
  "dot",
  "fan",
  "fig",
  "fin",
  "fit",
  "fog",
  "fun",
  "gap",
  "gem",
  "gum",
  "gun",
  "hip",
  "hug",
  "hum",
  "hut",
  "jar",
  "jaw",
  "lap",
  "law",
  "low",
  "raw",

  // ── The words the home row needs ───────────────────────────────────────────
  // No frequency list would put `flask` or `gala` in a top few thousand, and
  // lesson 7 is the reason they are here anyway: the alphabet at that point is
  // `a s d f g h j k l ;` and English has barely two dozen words in it. A
  // corpus that stopped at "common" would hand the first words lesson an empty
  // bag (§5.5 — words cannot start until lesson 7, and they have to start
  // there).
  "ash",
  "gas",
  "lad",
  "fad",
  "lag",
  "jag",
  "sag",
  "gash",
  "hash",
  "dash",
  "lash",
  "sash",
  "slash",
  "flash",
  "flask",
  "glass",
  "flag",
  "hall",
  "gall",
  "shall",
  "alas",
  "gala",
  "haddock",
  "shad",
  "adds",
  "asks",
  "falls",
  "lads",
  "flags",
  "halls",
  "flashes",

  // ── The words one hand needs ───────────────────────────────────────────────
  // Lesson 47 is "One hand at a time", and QWERTY is not symmetrical about it.
  // The left hand owns `a e r s t` and will write half a sentence on its own;
  // the right hand's alphabet is `h j k l m n o p u y`, and a corpus of common
  // words turns up barely thirty it can spell. These are the rest of them.
  "pupil",
  "union",
  "jolly",
  "holly",
  "hoop",
  "loop",
  "hook",
  "yolk",
  "junk",
  "limp",
  "lump",
  "link",
  "milky",
  "nylon",
  "monk",
  "kilo",
  "hymn",
  "lolly",
  "jumpy",

  // ── Contractions ───────────────────────────────────────────────────────────
  // The apostrophe arrives at lesson 35 and is the only punctuation mark a
  // word carries, so it is the only one this list may hold.
  "don't",
  "can't",
  "won't",
  "didn't",
  "doesn't",
  "isn't",
  "aren't",
  "wasn't",
  "weren't",
  "haven't",
  "hasn't",
  "hadn't",
  "couldn't",
  "wouldn't",
  "shouldn't",
  "it's",
  "that's",
  "there's",
  "here's",
  "what's",
  "let's",
  "I'm",
  "I've",
  "I'll",
  "I'd",
  "you're",
  "you'll",
  "we're",
  "we'll",
  "they're",
  "they'll",
  "he's",
  "she's",
  "we've",
  "they've",
];

/**
 * The commonest letter pairs in written English, commonest first.
 *
 * What lessons 18, 28, 42 and 43 drill (§5.6). A bigram lesson is not "type
 * these two letters" — it is a normal lesson whose words were chosen because
 * they contain the pair, which is why the corpus above has to be big enough to
 * offer a choice of them.
 */
export const BIGRAMS: readonly string[] = [
  "th",
  "he",
  "in",
  "er",
  "an",
  "re",
  "on",
  "at",
  "en",
  "nd",
  "ti",
  "es",
  "or",
  "te",
  "of",
  "ed",
  "is",
  "it",
  "al",
  "ar",
  "st",
  "to",
  "nt",
  "ng",
  "se",
  "ha",
  "as",
  "ou",
  "io",
  "le",
  "ve",
  "co",
  "me",
  "de",
  "hi",
  "ri",
  "ro",
  "ic",
  "ne",
  "ea",
  "ra",
  "ce",
  "li",
  "ch",
  "be",
  "ma",
  "si",
  "om",
  "ur",
];

/**
 * The letters that come in twos. Lesson 8, "Pairs that repeat".
 *
 * A double is the one sequence a beginner can be given before they can spell:
 * it is the same key twice, at lesson 8, when the alphabet is nine letters and
 * an ordinary word is still three lessons away. Ordered by how much use the
 * home row's alphabet can make of them, because that is the lesson that asks.
 */
export const DOUBLES: readonly string[] = [
  "ll",
  "ss",
  "dd",
  "ee",
  "oo",
  "tt",
  "ff",
  "rr",
  "nn",
  "pp",
  "mm",
  "cc",
  "gg",
  "bb",
];

/**
 * The pairs one finger has to type twice, which is what makes them hard.
 *
 * Lesson 44 is "The hard pairs" and lesson 84 sprints them, and the thing they
 * have in common is not that they are rare — `ed` is the sixteenth commonest
 * pair in the language. It is that both letters sit under the same finger:
 * `e` and `d` are both the left middle, `ju` and `ki` and `ny` are the right
 * index and middle doing the same thing. The hand cannot roll through them, so
 * they are where a fluent typist's speed actually goes, and they are worth a
 * lesson of their own precisely because no amount of ordinary practice singles
 * them out.
 *
 * Every pair here is checked against `strokeFor(...).finger` by the test, so a
 * pair that stops being same-finger — a second layout, one day — stops being
 * on this list rather than quietly becoming a lesson about nothing.
 */
export const HARD_PAIRS: readonly string[] = [
  "ed",
  "de",
  "ce",
  "ec",
  "un",
  "nu",
  "ju",
  "ki",
  "ik",
  "lo",
  "ol",
  "gr",
  "rg",
  "tr",
  "rt",
  "br",
  "rb",
  "ft",
  "hy",
  "ny",
  "my",
  "mu",
  "um",
  "sw",
  "ws",
];

/**
 * The commonest letter triples, commonest first.
 *
 * Three letters is where a pair stops being a reach and starts being a shape
 * the hand knows — `the`, `ing`, `ent` are typed as one movement by anybody
 * fluent, and a lesson that drills them is teaching that rather than teaching
 * spelling.
 */
export const TRIGRAMS: readonly string[] = [
  "the",
  "and",
  "ing",
  "her",
  "ent",
  "ion",
  "for",
  "tha",
  "ter",
  "ere",
  "est",
  "ers",
  "ver",
  "ith",
  "all",
  "ate",
  "out",
  "one",
  "hat",
  "his",
  "ell",
  "ght",
  "igh",
  "ake",
  "ill",
  "ome",
  "ave",
  "ust",
];

/**
 * Words the two hands take in turns. Lesson 46, "Hands that take turns".
 *
 * Every letter is on the other hand from the one before it, which is the
 * easiest thing a keyboard ever asks — the next finger is already moving while
 * the last one is still down. It is also the first time in the ladder that
 * speed comes from the layout rather than from effort, which is the point of
 * putting it here: block 5 is about fluency, and this is what fluency feels
 * like before a child has earned it everywhere else.
 *
 * Drawn from the corpus above rather than written separately, so a word cannot
 * be here and unknown to everything else. `lexicon.test.ts` checks both halves
 * — in `WORDS`, and genuinely alternating by `strokeFor(...).finger`.
 */
export const ALTERNATING: readonly string[] = [
  "with",
  "they",
  "their",
  "when",
  "make",
  "them",
  "than",
  "then",
  "also",
  "work",
  "down",
  "right",
  "land",
  "hand",
  "world",
  "such",
  "girl",
  "turn",
  "name",
  "city",
  "body",
  "half",
  "held",
  "both",
  "hair",
  "giant",
  "elbow",
  "laugh",
  "chair",
  "shelf",
  "soap",
  "bowl",
  "fork",
  "title",
  "shape",
  "duck",
  "lamb",
  "whale",
  "worm",
  "snake",
  "sock",
  "field",
  "island",
  "lake",
  "rock",
  "bush",
  "town",
  "lane",
  "handle",
  "bicycle",
  "eight",
  "pair",
  "wish",
  "spelt",
  "burnt",
  "paid",
  "spent",
  "kept",
  "slept",
  "busy",
  "ancient",
  "hang",
  "mend",
  "shake",
  "spend",
  "throw",
  "tidy",
  "visit",
  "height",
  "angle",
  "goal",
  "clay",
  "flame",
  "coal",
  "fuel",
  "blame",
  "keys",
];

/**
 * Words the left hand types on its own. Lesson 47, "One hand at a time".
 *
 * The opposite exercise to the one above, and the harder one: the same finger
 * comes back again and again, and the hand has to stay on the home row to do
 * it. Half of it is the reason the left hand is where `a e r s t` live —
 * English will write most of a sentence with one hand if you let it.
 */
export const LEFT_HAND: readonly string[] = [
  "was",
  "are",
  "were",
  "get",
  "see",
  "after",
  "read",
  "great",
  "water",
  "start",
  "tree",
  "ever",
  "red",
  "sea",
  "face",
  "far",
  "few",
  "car",
  "care",
  "sat",
  "dad",
  "ear",
  "feet",
  "tear",
  "better",
  "sad",
  "brave",
  "gate",
  "bed",
  "bag",
  "test",
  "edge",
  "cat",
  "rat",
  "bear",
  "deer",
  "zebra",
  "crab",
  "bee",
  "badger",
  "egg",
  "bread",
  "tea",
  "taste",
  "sweet",
  "scarf",
  "dress",
  "badge",
  "star",
  "wave",
  "grass",
  "seed",
  "street",
  "drew",
  "grew",
  "gave",
  "ate",
  "saw",
  "wet",
  "fast",
  "dead",
  "draw",
  "eat",
  "race",
  "save",
  "serve",
  "treat",
  "wear",
  "cave",
  "secret",
  "desert",
  "stage",
  "craft",
  "address",
  "fear",
  "cards",
  "trees",
  "stars",
  "cars",
];

/**
 * Words the right hand types on its own.
 *
 * There are barely thirty of them in a corpus this size, and that asymmetry is
 * a fact about QWERTY rather than a gap in the list: the right hand's alphabet
 * is `h j k l m n o p u y`, with no `a e s t r`, so most of what it can spell
 * is short. The lesson is the same length as the left-hand one anyway, which
 * means it repeats — and repeating a small set with one hand is the exercise.
 */
export const RIGHT_HAND: readonly string[] = [
  "you",
  "him",
  "look",
  "only",
  "mum",
  "puppy",
  "pony",
  "lion",
  "milk",
  "onion",
  "plum",
  "moon",
  "hill",
  "noon",
  "million",
  "jump",
  "hop",
  "pink",
  "join",
  "pull",
  "oil",
  "joy",
  "opinion",
  "ill",
  "ink",
  "lip",
  "mop",
  "pin",
  "pop",
  "pup",
  "hip",
  "hum",
  "pupil",
  "union",
  "jolly",
  "holly",
  "hoop",
  "loop",
  "hook",
  "yolk",
  "junk",
  "limp",
  "lump",
  "link",
  "milky",
  "nylon",
  "monk",
  "kilo",
  "hymn",
  "lolly",
  "jumpy",
];

/**
 * Whole sentences, for the lessons that ask for one (§5.6: 30, 36, 37, 38, 40).
 *
 * Written as a sentence is printed — a capital at the front, a stop at the end
 * — even though lesson 30 asks for sentences a full block before either shift
 * is taught. That is deliberate: the pool holds English, and folding the case
 * for a lesson that has no capitals yet is the generator's job, where the
 * unlocked alphabet is already in hand. A pool of lowercase sentences would be
 * a pool that block 4 could never use as it is.
 *
 * Graded by what they contain rather than by length, because that is what the
 * ladder filters on: plain letters and a full stop first, then commas, then
 * apostrophes, then question and exclamation marks, then speech marks, then
 * digits. A lesson takes the ones its alphabet can reach and the order above
 * is what makes sure there are enough of them at every level.
 *
 * Names are here rather than in `WORDS` because a name is only a name in a
 * sentence — a bare list of them is a list of capitalised nouns, and lesson 33
 * wants "Ravi and Grace waited at the gate", not "Ravi. Grace. Omar."
 */
export const SENTENCES: readonly string[] = [
  // Letters and a full stop. Everything the end of block 3 can reach.
  "The dog sat on the mat.",
  "A small bird landed on the fence.",
  "We walked home through the park.",
  "The old clock in the hall is slow.",
  "My sister found a shell on the sand.",
  "Rain fell all night on the roof.",
  "The cat slept in a patch of sun.",
  "Every apple on that tree is green.",
  "He carried the heavy box up the stairs.",
  "The bus stopped at the end of our road.",
  "She read the same book three times.",
  "A frog jumped into the cold pond.",
  "The bread came out of the oven warm.",
  "Ten sheep stood together in the field.",
  "We planted seeds along the garden path.",
  "The train left the station without us.",
  "A grey cloud covered the whole sky.",
  "Her house is the last one on the hill.",
  "The children painted a long paper banner.",
  "Snow lay thick on the roof of the shed.",
  "That horse can run faster than the wind.",
  "He kept the key under a flat stone.",
  "The lamp on the table went out.",
  "We found a nest in the tall hedge.",
  "A river runs behind the school.",
  "The market opens early on a Saturday.",
  "She washed the plates and dried them.",
  "The wind blew the gate open again.",
  "A ladder leant against the garden wall.",
  "Our team won the match by one goal.",

  // With commas. Lesson 37 is about exactly this.
  "We packed bread, cheese, apples and a bottle of water.",
  "After the rain, the whole street smelt of leaves.",
  "The puppy, who is only ten weeks old, sleeps all day.",
  "First we swept the floor, then we washed it.",
  "In the morning, before school, he feeds the hens.",
  "She likes reading, drawing and long walks by the river.",
  "If the bus is late, we will walk to the museum.",
  "The old man, leaning on his stick, waved at the train.",
  "Bring a coat, a hat and a pair of warm gloves.",
  "When the storm passed, the garden was covered in twigs.",
  "Slowly, quietly, the fox crossed the empty field.",
  "We climbed the hill, ate our lunch and came home.",
  "The shop sells paper, pens, glue and coloured card.",
  "Because it was snowing, the school stayed closed.",
  "He counted the coins, put them in a jar and smiled.",

  // Names and places. Lessons 33 and 38, once both shifts are taught.
  "Ravi and Grace waited at the gate.",
  "Sam found a lost dog on Oak Street.",
  "Mia read her poem to the whole class.",
  "Tom and Ada built a den in the wood.",
  "Nina lives in a cottage near the harbour.",
  "Omar carried the ladder round to the shed.",
  "Lily and Finn raced to the top of the hill.",
  "Jack helped his grandad plant the apple tree.",
  "Rosa painted a picture of the old lighthouse.",
  "Ben and Zoe went to the museum on Tuesday.",
  "Kai left his boots by the kitchen door.",
  "Priya counted twelve swans on the lake.",
  "Noah and his sister walked along Green Lane.",
  "Ivy watched the boats leave the harbour.",
  "Hassan brought a basket of plums to school.",
  "On Monday, Grace and Omar tidied the library.",
  "The bus to Oak Street leaves from the market.",
  "Ada and Ravi sang together on the stage.",

  // Apostrophes, from lesson 35.
  "It's raining again, so we can't play outside.",
  "Don't leave your boots on the kitchen floor.",
  "I'm sure that's the path we took last summer.",
  "She hasn't finished her book yet.",
  "They're building a bridge over the stream.",
  "We'll be home before it's dark.",
  "He didn't hear the bell because of the wind.",
  "That isn't my coat, it's my brother's.",
  "You'll like the story, though it's a long one.",
  "The dog wouldn't come in out of the rain.",
  "I've never seen so many stars.",
  "There's a robin's nest in the old hedge.",

  // Questions and shouts, from lesson 61.
  "Where did you put the map?",
  "Who left the gate open?",
  "How many apples are in the basket?",
  "What a beautiful morning it is!",
  "Can we walk to the beach after lunch?",
  "Look out, the paint is still wet!",
  "Why is the kitchen light on?",
  "Is that your bicycle by the wall?",
  "Hurry up, the bus is coming!",
  "When does the library open on a Sunday?",
  "Are these your gloves or mine?",
  "What a mess the wind has made!",

  // Speech marks, from lesson 62. Lesson 76 is a whole passage of them.
  '"Come and look at this," said Mia.',
  '"I think it is going to snow," said Grandad.',
  'Ravi shouted, "Wait for me!"',
  '"Who wants the last biscuit?" asked Mum.',
  '"We are nearly there," said Dad. "Keep walking."',
  '"That," said the teacher, "is a very good question."',
  '"Be careful on the ice," she warned.',
  '"Look," whispered Tom, "a deer."',

  // The rest of the marks, from lessons 63 to 68.
  "The well-known story begins on page 4.",
  "She wrote her name in capitals: GRACE.",
  "The recipe needs two things: flour and water.",
  "The old, well-loved book had a torn cover.",
  "He named the file winter_walk and saved it.",
  "The path (the muddy one) leads to the river.",
  "We paid 3 pounds for a bag of apples.",
  "Add 25 and 17, then take away 8.",
  "The shop opens at 9 and closes at 5.",
  "Our class has 28 children and 2 rabbits.",
  "She was born on 14 June 2019.",
  "The train leaves platform 3 at 10 past 7.",
  "Write to us at 12 Green Lane.",
  "The recipe makes 24 small buns.",
  "He ran 100 metres in 15 seconds.",
];

/**
 * Real prose, for the lessons that ask for a passage.
 *
 * From lesson 50 the ladder stops handing over words and starts handing over
 * paragraphs, because a passage is the only thing that teaches the two things
 * a word list cannot: where the space bar goes without thinking, and how to
 * keep a rate up for a hundred words rather than for thirty.
 *
 * Original prose, written for this file. Two reasons, and the second is the
 * one that matters: found text arrives with curly quotation marks, en dashes
 * and accented names, and typing marks exactly, so a passage carrying one is
 * unpassable rather than hard — the same trap the Scripture pool in
 * `decks/typing.ts` had to be picked around. The other reason is that nothing
 * here needs a credit line, which is what `Passage.credit` exists for and what
 * makes the copywork library the wrong place to shop.
 *
 * Sorted by what they hold, like the sentences: plain prose first, then
 * speech, then numbers. Lengths run from about fifty words to about a hundred
 * and thirty, which covers lesson 50 at one end and lesson 100's Ice Exam at
 * the other.
 */
export const PASSAGES: readonly string[] = [
  "The path to the beach runs between two high hedges. In summer it is full of bees, and the grass on either side grows taller than a child. At the end there is a gate, and beyond the gate the ground drops away into sand. On a still morning you can hear the sea long before you can see it. We walked down with our boots in our hands and found the tide out, the whole bay flat and shining, and not a single footprint on it but our own.",
  "Every autumn the old apple tree in the corner of the garden drops more fruit than we can carry. Some of it we pick, some of it the birds take, and the rest lies in the wet grass until the wasps find it. Grandad says the tree was planted the year he was born, which makes it older than the house. It leans a little to the left now, and one branch is held up by a wooden post, but it still gives us enough apples for a year of pies.",
  "The hedgehog was under the shed, curled tight and covered in dry leaves. We left a bowl of water near the gap and waited. For three nights nothing moved. On the fourth night the bowl was empty, and in the morning there were small tracks in the mud by the fence. Mum said the best thing we could do was leave it alone, so we did. By the end of the month the tracks reached all the way across the garden to the compost heap, and back again.",
  "Learning to ride a bicycle is mostly learning to trust the thing not to fall over. For a week I went up and down the lane with Dad holding the back of the seat, and every time he let go I stopped pedalling and put my feet down. Then one afternoon I got to the end of the lane and turned round before I noticed that he was standing by the gate, a long way behind me, with his hands in his pockets. I have not fallen off since.",
  "The library is warm in winter and cool in summer, which is more than can be said for our classroom. It has a low shelf near the window with the picture books on it, and a table where you are allowed to draw as long as you tidy up afterwards. The best day is Thursday, when the boxes come back from the other libraries and nobody knows what will be in them. I have found books about whales, about castles, and once about a girl who walked across a frozen lake.",
  "It snowed in the night, quietly, the way it always does. By breakfast the garden had lost its edges: the path, the flower beds and the low wall were one smooth white shape, and the shed had a thick roof of it. The birds came down to the place where the grass had been and stood about looking cross. We put out crumbs and half an apple, and then we went out ourselves and made a track all the way to the gate that spoilt the whole thing, which was the point.",
  "The den took two days to build and lasted until the first proper storm. We made the walls out of fallen branches leant against a low wall, and the roof out of an old sheet with stones on the corners. Inside there was room for three of us if nobody moved. We kept a tin of biscuits under a flat rock by the door, and a candle we were not allowed to light. When the wind took the roof off in October we found the biscuits were still dry, which felt like a kind of success.",
  "Rowing on the lake at dawn is the quietest thing I know. The water is grey and completely flat, and the oars make a sound like somebody turning the page of a very large book. Mist sits on the surface in patches and moves when you go through it. Once we saw a heron standing in the reeds, so still that we had gone past it before we understood what it was. By the time the sun is properly up the wind has started, the lake has small waves on it, and the morning is over.",
  '"Hold the end of it," said Dad, "and do not let go until I say." I held the end of it. The tent went up, more or less, and then it went sideways, and then it lay down in the grass like something that had given up. "Right," said Dad. "We will read the instructions." Mum laughed from the car. By the time it was dark we had a tent, a fire, and a rule that nobody was allowed to say the word tent again for the rest of the week.',
  '"Does anybody know why the sea is salty?" asked Mrs Hall. Nobody did. "Rivers," she said. "Rain falls on the hills, runs down through the rocks, and carries a little salt with it all the way to the sea. The water leaves again as cloud, but the salt stays behind." Ravi put his hand up. "So it is getting saltier?" he asked. "Very slowly," said Mrs Hall, "and it has been doing it for a very long time." We all looked out of the window at the rain.',
  "The market opens at 7 and is packed by 9. Apples are 2 pounds a bag, bread is 3, and the man on the corner stall sells 6 eggs for the price of 4 if you get there early. We had 15 pounds between us and a list of 8 things, which sounds like plenty until you add it up. In the end we came home with 5 bags, 2 loaves and no money at all, and Mum said that is exactly how a market is supposed to work.",
  "The moon is about 384 thousand kilometres away, which is roughly 30 Earths laid end to end. Light crosses that gap in 1 and a quarter seconds, so a radio message to somebody standing there takes about 2 and a half seconds to go and come back. The astronauts of 1969 took 3 days. They landed with 25 seconds of fuel left, walked about for 2 hours, and brought back 22 kilograms of rock, which is still being studied in laboratories today.",
];
